FROM python:3.10-slim

ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y \
    git \
    build-essential \
    libaio-dev \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN pip install --upgrade pip && pip install --no-cache-dir -r /app/requirements.txt

# No copies el código, lo montarás desde el host en el compose
# COPY . /app

EXPOSE 8083

CMD ["python", "main.py", "--runtime", "/app/runtime", "--log", "--mode", "webapp"]
